FROM python:3.10-alpine

WORKDIR /app

RUN apk update && apk add --no-cache \
    build-base \
    python3-dev \
    sdl2-dev \
    sdl2_image-dev \
    sdl2_ttf-dev \
    sdl2_mixer-dev

COPY . /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
